"""Build a fixture tree of genuinely-parseable files.

Synthetic bytes only exercise the failure paths. These are real PDFs, DOCX, XLSX, email
and images, so the extraction backends are tested against the formats they actually claim
to read.

Generated at test time rather than committed: binary fixtures rot silently, and a
generator makes what is in each file legible in the diff.
"""

from __future__ import annotations

import zlib
from pathlib import Path

INVOICE_TEXT = "\n".join(
    [
        "INVOICE",
        "Vendor: Northwind Traders",
        "Invoice No: INV-4471",
        "PO: PO-88120",
        "Date: 2024-02-11",
    ]
)


def write_pdf(path: Path, text: str) -> Path:
    """A minimal one-page PDF with a real text layer.

    Hand-built rather than generated by a library: PDF writers are a heavy dependency for
    a fixture, and the format is simple enough that assembling it here keeps the test
    honest about exactly what the extractor is being given.
    """
    lines = text.splitlines() or [""]
    content = "BT\n/F1 12 Tf\n72 720 Td\n14 TL\n"
    for line in lines:
        escaped = line.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
        content += f"({escaped}) Tj\nT*\n"
    content += "ET"
    stream = content.encode("latin-1")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    output = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for index, body in enumerate(objects, start=1):
        offsets.append(len(output))
        output += f"{index} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(output)
    output += f"xref\n0 {len(objects) + 1}\n".encode()
    output += b"0000000000 65535 f \n"
    for offset in offsets:
        output += f"{offset:010d} 00000 n \n".encode()
    output += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    ).encode()

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(output))
    return path


def write_scanned_pdf(path: Path) -> Path:
    """A PDF with no text layer at all — what a scan looks like to an extractor."""
    image = zlib.compress(bytes(64 * 64))
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /XObject << /Im1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /XObject /Subtype /Image /Width 64 /Height 64 /ColorSpace /DeviceGray "
        b"/BitsPerComponent 8 /Filter /FlateDecode /Length " + str(len(image)).encode()
        + b" >>\nstream\n" + image + b"\nendstream",
        b"<< /Length 44 >>\nstream\nq 612 0 0 792 0 0 cm /Im1 Do Q\nendstream",
    ]
    output = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for index, body in enumerate(objects, start=1):
        offsets.append(len(output))
        output += f"{index} 0 obj\n".encode() + body + b"\nendobj\n"
    xref_at = len(output)
    output += f"xref\n0 {len(objects) + 1}\n".encode() + b"0000000000 65535 f \n"
    for offset in offsets:
        output += f"{offset:010d} 00000 n \n".encode()
    output += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    ).encode()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(output))
    return path


def write_docx(path: Path, text: str) -> Path:
    import docx

    path.parent.mkdir(parents=True, exist_ok=True)
    document = docx.Document()
    for line in text.splitlines():
        document.add_paragraph(line)
    # Several line items, so the fixture is long enough to exercise a char limit.
    items = [("Widgets, 10cm", "480.00"), ("Freight", "72.50"), ("Total", "1234.50")]
    table = document.add_table(rows=len(items), cols=2)
    for row, (label, amount) in enumerate(items):
        table.cell(row, 0).text = label
        table.cell(row, 1).text = amount
    document.save(str(path))
    return path


def write_xlsx(path: Path) -> Path:
    import openpyxl

    path.parent.mkdir(parents=True, exist_ok=True)
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = "Invoice"
    sheet.append(["Vendor", "Invoice No", "PO", "Total"])
    sheet.append(["Contoso Supply Co", "INV-10233", "PO-55004", 4821.00])
    workbook.save(str(path))
    return path


def write_eml(path: Path) -> Path:
    from email.message import EmailMessage

    path.parent.mkdir(parents=True, exist_ok=True)
    message = EmailMessage()
    message["From"] = "billing@northwind.example"
    message["To"] = "ap@acme.example"
    message["Subject"] = "Invoice INV-4472"
    message["Date"] = "Sun, 03 Mar 2024 09:15:00 +0000"
    message.set_content("Please find invoice INV-4472 attached. PO-88121. Due 2024-04-02.")
    path.write_bytes(message.as_bytes())
    return path


def write_png(path: Path) -> Path:
    from PIL import Image, ImageDraw

    path.parent.mkdir(parents=True, exist_ok=True)
    image = Image.new("RGB", (480, 120), "white")
    ImageDraw.Draw(image).text((10, 40), "INVOICE INV-9001 PO-33001", fill="black")
    image.save(str(path))
    return path


def build_tree(root: Path) -> dict[str, Path]:
    """The awkward cases, not just the happy ones."""
    root.mkdir(parents=True, exist_ok=True)
    created = {
        "digital_pdf": write_pdf(root / "2024" / "q1" / "invoice_4471.pdf", INVOICE_TEXT),
        "scanned_pdf": write_scanned_pdf(root / "2024" / "q1" / "scan_no_text.pdf"),
        "docx": write_docx(root / "2024" / "q2" / "invoice_note.docx", INVOICE_TEXT),
        "xlsx": write_xlsx(root / "2024" / "q2" / "ledger.xlsx"),
        "eml": write_eml(root / "mail" / "invoice_4472.eml"),
        "png": write_png(root / "scans" / "IMG_9001.png"),
    }

    empty = root / "empty.pdf"
    empty.write_bytes(b"")
    created["zero_byte"] = empty

    unreadable = root / "locked.pdf"
    unreadable.write_bytes(b"%PDF-1.4\n")
    unreadable.chmod(0o000)
    created["permission_denied"] = unreadable

    return created


def cleanup(root: Path) -> None:
    """Restore permissions so pytest's tmp_path teardown can remove the tree."""
    for path in root.rglob("*"):
        if path.is_file():
            path.chmod(0o644)
